"""added position field to set and sethistory fix

Revision ID: ad83c0f29b8e
Revises: eea414ca6ac7
Create Date: 2023-03-05 14:02:28.622501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad83c0f29b8e'
down_revision = 'eea414ca6ac7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sets', 'position')
    op.drop_column('set_histories', 'position')    # ### end Alembic commands ###
    op.add_column('set_histories', sa.Column('position', sa.Integer(), nullable=True))
    op.add_column('sets', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


    # ### commands auto generated by Alembic - please adjust! ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE set_histories MODIFY COLUMN position INTEGER NULL')
    op.execute('ALTER TABLE sets MODIFY COLUMN position INTEGER NULL')
    # ### end Alembic commands ###
