"""added position field to set and sethistory

Revision ID: eea414ca6ac7
Revises: 006c660adb29
Create Date: 2023-03-05 13:56:16.826882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eea414ca6ac7'
down_revision = '006c660adb29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('set_histories', sa.Column('position', sa.Integer(), nullable=True))
    op.add_column('sets', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sets', 'position')
    op.drop_column('set_histories', 'position')
    # ### end Alembic commands ###
